name: Build Multi-Arch Docker Images

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        default: "v2.9.1"
        description: The https://github.com/openebs/mayastor-extensions git tag to pull & build

jobs:
  build:
    permissions:
      packages: write
    strategy:
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    outputs:
      images: ${{ steps.push-images.outputs.images }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: openebs/mayastor-extensions
          ref: ${{ inputs.tag }}
          submodules: 'recursive'
          fetch-depth: 0
      - run: |
          # BUG: HEAD tag is fetched as lightweight instead of annotated
          # https://github.com/actions/checkout/issues/290
          if [ "${{ github.ref_type }}" == "tag" ]; then
            git fetch -f origin ${{ github.ref }}:${{ github.ref }}
          fi

      - uses: cachix/install-nix-action@v31.3.0
      - name: Build and push the release images
        run: ./scripts/release.sh --skip-publish

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push single-arch images
        id: push-images
        run: |
          images=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep -v "<none>" | sort -u | tr '\n' ' ')
          echo "images='$images'" >> "$GITHUB_OUTPUT"
          mkdir -p openebs
          for image in $images; do
            [[ "${{ matrix.runner }}" == *-arm ]] && arch="arm64" || arch="amd64"
            new_tag="ghcr.io/${{ github.repository_owner }}/$image-$arch"
            echo "Pushing image '$image' to '$new_tag'"
            docker tag $image $new_tag
            docker push $new_tag
          done
  merge:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull, merge & push images
        run: |
          # For some reason gh doesn't like the space delimted images string
          # So we pass it as a literal and echo it so that bash can iterate over it
          for image in $(echo ${{ needs.build.outputs.images }}); do
            echo "Merging image '$image'"
            docker pull "ghcr.io/${{ github.repository_owner }}/$image-amd64"
            docker pull "ghcr.io/${{ github.repository_owner }}/$image-arm64"
            docker manifest create "ghcr.io/${{ github.repository_owner }}/$image" \
              --amend "ghcr.io/${{ github.repository_owner }}/$image-amd64" \
              --amend "ghcr.io/${{ github.repository_owner }}/$image-arm64"
            docker manifest push "ghcr.io/${{ github.repository_owner }}/$image"
          done
